name: Bug report
description: Create a report to help us improve
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: Describe the bug
      description: |
        Please fill out this template to the best of your ability. You can always edit this issue once you have created it.
        Read the following [link](https://github.com/retrospect-addon/plugin.video.retrospect/wiki/Troubleshooting) before you create a new problem report.
        Before you start make sure that you are running the latest Kodi and Retrospect version. Also check that you can watch the tv show online in a web browser.
      placeholder: |
        Provide a more detailed introduction to the issue itself, and why you consider it to be a bug
        A bug report that is not clear will be closed
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: Expected Behavior
      description: |
        Tell us what should happen
      placeholder: |
        Write here!
    validations:
      required: true

  - type: textarea
    attributes:
      label: Actual Behavior
      description: |
        Tell us what happens instead
      placeholder: |
        Write here!
    validations:
      required: true

  - type: textarea
    attributes:
      label: Possible Fix
      description: |
        Not obligatory, but suggest a fix or reason for the bug
      placeholder: |
        Write here!
    validations:
      required: false

  - type: textarea
    attributes:
      label: To Reproduce
      description: |
        Steps to reproduce the behavior:
        Provide a link to a live example, or an unambiguous set of steps to
        reproduce this bug. Include code to reproduce, if relevant
      placeholder: |
        1.
        2.
        3.
    validations:
      required: false
