name: Bug report
desciption: Create a report to help us improve
body:
  - type: textarea
    attributes:
      label: Bug report
      description: |
        Please fill out this template to the best of your ability. You can always edit this issue once you have created it.
        Read the following link before you create a new problem report: https://github.com/retrospect-addon/plugin.video.retrospect/wiki/Troubleshooting
        Before you start make sure that you are running the latest Kodi and Retrospect version. Also check that you can watch the tv show online in a webbrowser.
      placeholder: |
        Provide a more detailed introduction to the issue itself, and why you consider it to be a bug
        A bug report that is not clear will be closed
    validations:
      required: true
